openapi: 3.0.3
info:
  title: GitHub API (subset for PR merge)
  version: v3
servers:
  - url: https://api.github.com
paths:
  /repos/{owner}/{repo}/pulls/{pull_number}:
    get:
      summary: Get pull request
      parameters:
        - in: path
          name: owner
          required: true
          schema:
            type: string
        - in: path
          name: repo
          required: true
          schema:
            type: string
        - in: path
          name: pull_number
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Pull request details
          content:
            application/json:
              schema:
                type: object
                properties:
                  number:
                    type: integer
                  state:
                    type: string
                  mergeable:
                    type: boolean
                  mergeable_state:
                    type: string
                  head:
                    type: object
                    properties:
                      sha:
                        type: string
  /repos/{owner}/{repo}/pulls/{pull_number}/merge:
    put:
      summary: Merge pull request
      parameters:
        - in: path
          name: owner
          required: true
          schema:
            type: string
        - in: path
          name: repo
          required: true
          schema:
            type: string
        - in: path
          name: pull_number
          required: true
          schema:
            type: integer
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                merge_method:
                  type: string
                  enum: [merge, squash, rebase]
                commit_title:
                  type: string
      responses:
        "200":
          description: Merge result
          content:
            application/json:
              schema:
                type: object
                properties:
                  merged:
                    type: boolean
                  message:
                    type: string
