openapi: 3.0.3
info:
  title: GitHub API (Subset)
  version: 1.0.0
servers:
  - url: https://api.github.com
paths:
  /repos/{owner}/{repo}:
    get:
      summary: Get repository
      security:
        - bearerAuth: []
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: repo
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Repository details
  /repos/{owner}/{repo}/pulls/{pull_number}/merge:
    put:
      summary: Merge pull request
      security:
        - bearerAuth: []
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: repo
          in: path
          required: true
          schema:
            type: string
        - name: pull_number
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                merge_method:
                  type: string
      responses:
        "200":
          description: Merge result
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
